  ai[m
  authorization[m
  automated-building[m
  backend-v2[m
  backend_v1[m
  calorie-feature[m
  competition-fixed[m
  counting[m
  diet-feature[m
  diet-modified[m
  diet-validation-fixed[m
* [32mdocumentation[m
  final-feature[m
  fixed-gym-feature[m
  fixed-schedules-api[m
  frontend_v2[m
  gym-feature[m
  gym-getall-fixed[m
  image-handling[m
  main[m
  pagination-error-fixed[m
  refactored-files[m
  statistics-load-balanced-feature[m
  stripe[m
  testing[m
